LocadoraDeVeiculos.WebApp/Models/LocacaoViewModel.cs
using LocadoraDeVeiculos.Dominio.ModuloLocacao;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LocadoraDeVeiculos.WebApp.Models;

public class FormularioLocacaoViewModel
{
    [Required(ErrorMessage = "O veículo é obrigatório")]
    public int VeiculoId { get; set; }

    [Required(ErrorMessage = "O condutor é obrigatório")]
    public int CondutorId { get; set; }

    [Required(ErrorMessage = "O tipo de plano é obrigatório")]
    public TipoPlanoCobrancaEnum TipoPlano { get; set; }

    [Required(ErrorMessage = "O marcador de combustível é obrigatório")]
    public MarcadorCombustivelEnum MarcadorCombustivel { get; set; }

    [Required(ErrorMessage = "A quilometragem percorrida é obrigatória")]
    [Range(0, int.MaxValue, ErrorMessage = "A quilometragem percorrida deve ser maior ou igual a 0")]
    public int QuilometragemPercorrida { get; set; }

    [Required(ErrorMessage = "A data da locação é obrigatória")]
    [DataType(DataType.Date)]
    public DateTime DataLocacao { get; set; }

    [Required(ErrorMessage = "A data prevista de devolução é obrigatória")]
    [DataType(DataType.Date)]
    public DateTime DevolucaoPrevista { get; set; }

    public IEnumerable<int> TaxasSelecionadas { get; set; }

    public IEnumerable<SelectListItem>? Veiculos { get; set; }
    public IEnumerable<SelectListItem>? Condutores { get; set; }
    public IEnumerable<SelectListItem>? Taxas { get; set; }

    public FormularioLocacaoViewModel()
    {
        DataLocacao = DateTime.Now;
        DevolucaoPrevista = DateTime.Now.AddDays(1);
        MarcadorCombustivel = MarcadorCombustivelEnum.Completo;
    }
}

public class InserirLocacaoViewModel : FormularioLocacaoViewModel
{
}

public class EditarLocacaoViewModel : FormularioLocacaoViewModel
{
    public int Id { get; set; }
}

public class RealizarDevolucaoViewModel : FormularioLocacaoViewModel
{
    public int Id { get; set; }
}

public class ConfirmarAberturaLocacaoViewModel : FormularioLocacaoViewModel
{
    public decimal ValorParcial { get; set; }
}

public class ConfirmarDevolucaoLocacaoViewModel : FormularioLocacaoViewModel
{
    public int Id { get; set; }
    public decimal ValorTotal { get; set; }
}

public class ListarLocacaoViewModel
{
    public int Id { get; set; }
    public string Veiculo { get; set; }
    public string Condutor { get; set; }
    public string TipoPlano { get; set; }
    public int QuilometragemPercorrida { get; set; }
    public DateTime DataLocacao { get; set; }
    public DateTime DevolucaoPrevista { get; set; }
    public DateTime? DataDevolucao { get; set; }
}

public class DetalhesLocacaoViewModel
{
    public int Id { get; set; }
    public string Veiculo { get; set; }
    public string Condutor { get; set; }
    public string TipoPlano { get; set; }
    public string MarcadorCombustivel { get; set; }
    public int QuilometragemPercorrida { get; set; }
    public DateTime DataLocacao { get; set; }
    public DateTime DevolucaoPrevista { get; set; }
    public DateTime? DataDevolucao { get; set; }
}

LocadoraDeVeiculos.WebApp/Controllers/LocacaoController.cs
using AutoMapper;
using LocadoraDeVeiculos.Aplicacao.ModuloAutenticacao;
using LocadoraDeVeiculos.Aplicacao.ModuloCondutor;
using LocadoraDeVeiculos.Aplicacao.ModuloLocacao;
using LocadoraDeVeiculos.Aplicacao.ModuloTaxa;
using LocadoraDeVeiculos.Aplicacao.ModuloVeiculo;
using LocadoraDeVeiculos.Dominio.ModuloLocacao;
using LocadoraDeVeiculos.WebApp.Controllers.Compartilhado;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;

namespace LocadoraDeVeiculos.WebApp.Controllers;

[Authorize(Roles = "Empresa,Funcionario")]
public class LocacaoController : WebControllerBase
{
    private readonly ServicoLocacao servicoLocacao;
    private readonly ServicoVeiculo servicoVeiculo;
    private readonly ServicoCondutor servicoCondutor;
    private readonly ServicoTaxa servicoTaxa;
    private readonly IMapper mapeador;

    public LocacaoController(
        ServicoAutenticacao servicoAuth,
        ServicoLocacao servicoLocacao,
        ServicoVeiculo servicoVeiculo,
        ServicoCondutor servicoCondutor,
        ServicoTaxa servicoTaxa,
        IMapper mapeador
    ) : base(servicoAuth)
    {
        this.servicoLocacao = servicoLocacao;
        this.servicoVeiculo = servicoVeiculo;
        this.servicoCondutor = servicoCondutor;
        this.servicoTaxa = servicoTaxa;
        this.mapeador = mapeador;
    }
    public IActionResult Listar()
    {
        var resultado = servicoLocacao.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var locacoes = resultado.Value;

        var listarLocacoesVm = mapeador.Map<IEnumerable<ListarLocacaoViewModel>>(locacoes);

        return View(listarLocacoesVm);
    }

    public IActionResult Inserir()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Inserir(InserirLocacaoViewModel inserirVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(inserirVm));

        var locacao = mapeador.Map<Locacao>(inserirVm);

        var confirmarVm = mapeador.Map<ConfirmarAberturaLocacaoViewModel>(locacao);

        TempData["LocacaoParaInsercao"] = JsonSerializer.Serialize(confirmarVm);

        return RedirectToAction("ConfirmarAbertura");
    }
    public IActionResult ConfirmarAbertura()
    {
        if (TempData["LocacaoParaInsercao"] is null)
            return RedirectToAction(nameof(Inserir));

        var locacaoDataJson = TempData["LocacaoParaInsercao"]!.ToString();

        var confirmarVm = JsonSerializer.Deserialize<ConfirmarAberturaLocacaoViewModel>(locacaoDataJson);

        return View(confirmarVm);
    }

    [HttpPost]
    public IActionResult ConfirmarAbertura(ConfirmarAberturaLocacaoViewModel confirmarVm)
    {
        var locacao = mapeador.Map<Locacao>(confirmarVm);

        var resultado = servicoLocacao.Inserir(locacao);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"A locação ID [{locacao.Id}] foi aberta com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult RealizarDevolucao(int id)
    {
        var resultado = servicoLocacao.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var locacao = resultado.Value;

        var devolucaoVm = mapeador.Map<RealizarDevolucaoViewModel>(locacao);

        return View(devolucaoVm);
    }

    [HttpPost]
    public IActionResult RealizarDevolucao(RealizarDevolucaoViewModel devolucaoVm)
    {
        var locacao = mapeador.Map<Locacao>(devolucaoVm);

        var confirmarVm = mapeador.Map<ConfirmarDevolucaoLocacaoViewModel>(locacao);

        TempData["LocacaoParaDevolucao"] = JsonSerializer.Serialize(confirmarVm);

        return RedirectToAction("ConfirmarDevolucao");

    }

    public IActionResult ConfirmarDevolucao()
    {
        if (TempData["LocacaoParaDevolucao"] is null)
            return RedirectToAction(nameof(Listar));

        var locacaoDataJson = TempData["LocacaoParaDevolucao"]!.ToString();

        var confirmarVm = JsonSerializer.Deserialize<ConfirmarDevolucaoLocacaoViewModel>(locacaoDataJson);

        return View(confirmarVm);
    }

    [HttpPost]
    public IActionResult ConfirmarDevolucao(ConfirmarDevolucaoLocacaoViewModel confirmarVm)
    {
        var locacaoOriginal = servicoLocacao.SelecionarPorId(confirmarVm.Id).Value;

        var locacaoAtualizada = mapeador.Map<ConfirmarDevolucaoLocacaoViewModel, Locacao>(confirmarVm, locacaoOriginal);

        var resultado = servicoLocacao.RealizarDevolucao(locacaoAtualizada);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"A locação ID [{locacaoAtualizada.Id}] foi concluída com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    private InserirLocacaoViewModel CarregarDadosFormulario(InserirLocacaoViewModel? formularioVm = null)
    {
        var condutores = servicoCondutor.SelecionarTodos(EmpresaId.GetValueOrDefault()).Value;
        var veiculos = servicoVeiculo.SelecionarTodos(EmpresaId.GetValueOrDefault()).Value;
        var taxas = servicoTaxa.SelecionarTodos(EmpresaId.GetValueOrDefault()).Value;

        if (formularioVm is null)
            formularioVm = new InserirLocacaoViewModel();

        formularioVm.Condutores =
            condutores.Select(c => new SelectListItem(c.Nome, c.Id.ToString()));

        formularioVm.Veiculos =
            veiculos.Select(c => new SelectListItem(c.Modelo, c.Id.ToString()));

        formularioVm.Taxas =
            taxas.Select(c => new SelectListItem(c.ToString(), c.Id.ToString()));

        return formularioVm;
    }
}

LocadoraDeVeiculos.WebApp/Views/Locacao/ConfirmarAbertura.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model LocadoraDeVeiculos.WebApp.Models.ConfirmarAberturaLocacaoViewModel

@{
    ViewBag.Title = "Confirmar Abertura de Locação";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="ConfirmarAbertura">

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number" readonly />
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" min="@DateTime.Today" readonly />
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" min="@DateTime.Today" readonly />
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple readonly></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <p><strong>Valor Parcial:</strong> @Model.ValorParcial.ToString("C2") + <em class="text-success">@(1000m.ToString("C2")) de caução</em></p>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Inserir">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/ConfirmarDevolucao.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model LocadoraDeVeiculos.WebApp.Models.ConfirmarDevolucaoLocacaoViewModel

@{
    ViewBag.Title = "Confirmar Devolução de Locação";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="ConfirmarDevolucao">
            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Id</label>
                <input class="form-control mb-1" asp-for="Id" readonly />
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number" readonly />
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" min="@DateTime.Today" readonly />
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" min="@DateTime.Today" readonly />
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple readonly></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <p><strong>Valor Total:</strong> @Model.ValorTotal.ToString("C2")</p>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/Detalhes.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesLocacaoViewModel
@{
	ViewBag.Title = "Detalhes da Locação";
}

<div class="col">
	<partial name="_Informacoes" model="Model"></partial>

	<a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
		<i class="bi bi-arrow-return-left me-1"></i>
		Voltar
	</a>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/Excluir.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesLocacaoViewModel

@{
	ViewBag.Title = "Excluir Locação";
}

<div class="col">
	<partial name="_Informacoes" model="Model"></partial>

	<form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
		<button class="btn btn-danger px-5">
			<i class="bi bi-trash-fill me-1"></i>
			Confirmar
		</button>

		<a class="btn btn-outline-primary px-5" asp-action="Listar">
			<i class="bi bi-arrow-return-left me-1"></i>
			Voltar
		</a>
	</form>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/Inserir.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model LocadoraDeVeiculos.WebApp.Models.InserirLocacaoViewModel

@{
    ViewBag.Title = "Inserir Locação";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos">
                    @if (Model.Veiculos is null || !Model.Veiculos.Any())
                    {
                        <option value="0" disabled>Nenhum veículo disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores">
                    @if (Model.Condutores is null || !Model.Condutores.Any())
                    {
                        <option value="0" disabled>Nenhum condutor disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()"></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number" readonly />
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" min="@DateTime.Today" />
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" min="@DateTime.Today" />
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/Listar.cshtml
@model IEnumerable<LocadoraDeVeiculos.WebApp.Models.ListarLocacaoViewModel>

@{
    ViewBag.Title = "Listagem de Locações";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="Locacao" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Nova Locação
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var locacaoVm in Model)
        {
        <div class="card col-lg-4 col-xl-3 px-0">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                <h5 class="p-0">Locação #@locacaoVm.Id</h5>

                <div class="text-end d-flex align-items-center gap-3">
                    @if (!locacaoVm.DataDevolucao.HasValue)
                    {
                        <a title="Realizar Devolução"
                           class="text-info-emphasis fs-5"
                           href="/Locacao/RealizarDevolucao/@locacaoVm.Id">
                            <i class="bi bi-coin"></i>
                        </a>
                    }
                    <a title="Detalhes"
                       class="text-info-emphasis fs-5"
                       href="/Locacao/Detalhes/@locacaoVm.Id">
                        <i class="bi bi-search"></i>
                    </a>
                    @if (!locacaoVm.DataDevolucao.HasValue)
                    {
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/Locacao/Editar/@locacaoVm.Id">
                            <i class="bi bi-pencil"></i>
                        </a>    
                    }
                    @if (locacaoVm.DataDevolucao.HasValue)
                    {
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/Locacao/Excluir/@locacaoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    }
                </div>
            </div>

            <div class="card-body">
                <h5 class="card-title">Veículo: @locacaoVm.Veiculo</h5>
                <p class="card-text">
                    Condutor: @locacaoVm.Condutor <br />
                    Tipo de Plano: @locacaoVm.TipoPlano <br />

                    <hr>
        
                    Devolução: @(locacaoVm.DataDevolucao.HasValue ? "Completa" : "Pendente")<br />
                    Data da Locação: @locacaoVm.DataLocacao.ToShortDateString()<br />
                    Data Prevista de Devolução: @locacaoVm.DevolucaoPrevista.ToShortDateString()<br />
                    
                    @if (locacaoVm.DataDevolucao.HasValue)
                    { 
                        <span>Data de Devolução: @locacaoVm.DataDevolucao.Value.ToShortDateString()</span><br />
                        <span>Quilometragem Percorrida: @locacaoVm.QuilometragemPercorrida km(s)</span><br />
                    }
                </p>
            </div>
        </div>
        }
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/Locacao/_Informacoes.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesLocacaoViewModel

<div class="row gap-3 my-3 my-xl-5">
	<label class="fs-4"><strong>Veículo:</strong> @Model.Veiculo</label>

	<label class="fs-4"><strong>Condutor:</strong> @Model.Condutor</label>

	<label class="fs-4"><strong>Tipo de Plano:</strong> @Model.TipoPlano</label>

	<label class="fs-4"><strong>Marcador de Combustível:</strong> @Model.MarcadorCombustivel</label>

	<label class="fs-4"><strong>Quilometragem Percorrida:</strong> @Model.QuilometragemPercorrida km</label>

	<label class="fs-4"><strong>Data de Locação:</strong> @Model.DataLocacao.ToShortDateString()</label>

	<label class="fs-4"><strong>Devolução Prevista:</strong> @Model.DevolucaoPrevista.ToShortDateString()</label>

	@if(Model.DataDevolucao.HasValue)
	{
		<label class="fs-4"><strong>Data de Devolução:</strong> @Model.DataDevolucao.Value.ToShortDateString()</label>
	}
	else
	{
		<label class="fs-4"><strong>Data de Devolução:</strong> Não devolvido</label>
	}

	<label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>