LocadoraDeVeiculos.WebApp/Models/PlanoCobrancaViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LocadoraDeVeiculos.WebApp.Models;

public class FormularioPlanoCobrancaViewModel
{
    [Required(ErrorMessage = "O grupo de veículos é obrigatório")]
    public int GrupoVeiculosId { get; set; }

    [Required(ErrorMessage = "O preço diário do plano diário é obrigatório")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço diário do plano diário deve ser maior que 0")]
    public decimal PrecoDiarioPlanoDiario { get; set; }

    [Required(ErrorMessage = "O preço por quilômetro do plano diário é obrigatório")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço por quilômetro do plano diário deve ser maior que 0")]
    public decimal PrecoQuilometroPlanoDiario { get; set; }

    [Required(ErrorMessage = "Os quilômetros disponíveis no plano controlado são obrigatórios")]
    [Range(0.01, double.MaxValue, ErrorMessage = "Os quilômetros disponíveis no plano controlado devem ser maiores que 0")]
    public decimal QuilometrosDisponiveisPlanoControlado { get; set; }

    [Required(ErrorMessage = "O preço diário do plano controlado é obrigatório")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço diário do plano controlado deve ser maior que 0")]
    public decimal PrecoDiarioPlanoControlado { get; set; }

    [Required(ErrorMessage = "O preço por quilômetro extrapolado no plano controlado é obrigatório")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço por quilômetro extrapolado no plano controlado deve ser maior que 0")]
    public decimal PrecoQuilometroExtrapoladoPlanoControlado { get; set; }

    [Required(ErrorMessage = "O preço diário do plano livre é obrigatório")]
    [Range(0.01, double.MaxValue, ErrorMessage = "O preço diário do plano livre deve ser maior que 0")]
    public decimal PrecoDiarioPlanoLivre { get; set; }

    public IEnumerable<SelectListItem>? GruposVeiculos { get; set; }
}

public class InserirPlanoCobrancaViewModel : FormularioPlanoCobrancaViewModel
{

}

public class EditarPlanoCobrancaViewModel : FormularioPlanoCobrancaViewModel
{
    public int Id { get; set; }
}

public class ListarPlanoCobrancaViewModel
{
    public int Id { get; set; }
    public string GrupoVeiculos { get; set; }
    public decimal PrecoDiarioPlanoDiario { get; set; }
    public decimal PrecoQuilometroPlanoDiario { get; set; }
    public decimal QuilometrosDisponiveisPlanoControlado { get; set; }
    public decimal PrecoDiarioPlanoControlado { get; set; }
    public decimal PrecoQuilometroExtrapoladoPlanoControlado { get; set; }
    public decimal PrecoDiarioPlanoLivre { get; set; }
}

public class DetalhesPlanoCobrancaViewModel
{
    public int Id { get; set; }
    public string GrupoVeiculos { get; set; }
    public decimal PrecoDiarioPlanoDiario { get; set; }
    public decimal PrecoQuilometroPlanoDiario { get; set; }
    public decimal QuilometrosDisponiveisPlanoControlado { get; set; }
    public decimal PrecoDiarioPlanoControlado { get; set; }
    public decimal PrecoQuilometroExtrapoladoPlanoControlado { get; set; }
    public decimal PrecoDiarioPlanoLivre { get; set; }
}

LocadoraDeVeiculos.WebApp/Controllers/PlanoCobrancaController.cs
using AutoMapper;
using LocadoraDeVeiculos.Aplicacao.ModuloAutenticacao;
using LocadoraDeVeiculos.Aplicacao.ModuloPlanoCobranca;
using LocadoraDeVeiculos.Aplicacao.Servicos;
using LocadoraDeVeiculos.Dominio.ModuloPlanoCobranca;
using LocadoraDeVeiculos.WebApp.Controllers.Compartilhado;
using LocadoraDeVeiculos.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LocadoraDeVeiculos.WebApp.Controllers;

[Authorize(Roles = "Empresa,Funcionario")]
public class PlanoCobrancaController : WebControllerBase
{
    private readonly ServicoPlanoCobranca servico;
    private readonly ServicoGrupoVeiculos servicoGrupos;
    private readonly IMapper mapeador;

    public PlanoCobrancaController(
        ServicoAutenticacao servicoAuth,
        ServicoPlanoCobranca servico,
        ServicoGrupoVeiculos servicoGrupos,
        IMapper mapeador) : base(servicoAuth)
    {
        this.servico = servico;
        this.servicoGrupos = servicoGrupos;
        this.mapeador = mapeador;
    }

    public IActionResult Listar()
    {
        var resultado = servico.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var planosCobranca = resultado.Value;

        var listarPlanosVm = mapeador.Map<IEnumerable<ListarPlanoCobrancaViewModel>>(planosCobranca);

        return View(listarPlanosVm);
    }

    public IActionResult Inserir()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Inserir(InserirPlanoCobrancaViewModel inserirVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(inserirVm));

        var planoCobranca = mapeador.Map<PlanoCobranca>(inserirVm);

        var resultado = servico.Inserir(planoCobranca);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{planoCobranca.Id}] foi inserido com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Editar(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var planoCobranca = resultado.Value;

        var editarVm = mapeador.Map<EditarPlanoCobrancaViewModel>(planoCobranca);

        var grupos = servicoGrupos.SelecionarTodos(EmpresaId.GetValueOrDefault()).Value;

        editarVm.GruposVeiculos = grupos
            .Select(g => new SelectListItem(g.Nome, g.Id.ToString()));

        return View(editarVm);
    }

    [HttpPost]
    public async Task<IActionResult> Editar(EditarPlanoCobrancaViewModel editarVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(editarVm));

        var planoCobranca = mapeador.Map<PlanoCobranca>(editarVm);

        var resultado = servico.Editar(planoCobranca);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{planoCobranca.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var planoCobranca = resultado.Value;

        var detalhesVm = mapeador.Map<DetalhesPlanoCobrancaViewModel>(planoCobranca);

        return View(detalhesVm);
    }

    [HttpPost]
    public IActionResult Excluir(DetalhesPlanoCobrancaViewModel detalhesVm)
    {
        var resultado = servico.Excluir(detalhesVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{detalhesVm.Id}] foi excluído com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var planoCobranca = resultado.Value;

        var detalhesVm = mapeador.Map<DetalhesPlanoCobrancaViewModel>(planoCobranca);

        return View(detalhesVm);
    }

    private FormularioPlanoCobrancaViewModel? CarregarDadosFormulario(FormularioPlanoCobrancaViewModel? dadosPrevios = null)
    {
        var resultadoGrupos = servicoGrupos.SelecionarTodos(EmpresaId.GetValueOrDefault());

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());

            return null;
        }

        if (dadosPrevios is null)
        {
            var formularioVm = new FormularioPlanoCobrancaViewModel
            {
                GruposVeiculos = resultadoGrupos.Value
                    .Select(g => new SelectListItem(g.Nome, g.Id.ToString()))
            };

            return formularioVm;
        }

        dadosPrevios.GruposVeiculos = resultadoGrupos.Value
            .Select(g => new SelectListItem(g.Nome, g.Id.ToString()));

        return dadosPrevios;
    }
}

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/Detalhes.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesPlanoCobrancaViewModel

@{
	ViewBag.Title = "Detalhes do Plano de Cobrança";
}

<div class="col">
	<partial name="_Informacoes" model="Model"></partial>

	<a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
		<i class="bi bi-arrow-return-left me-1"></i>
		Voltar
	</a>
</div>

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/Editar.cshtml
@model LocadoraDeVeiculos.WebApp.Models.FormularioPlanoCobrancaViewModel

@{
ViewBag.Title = "Editar Plano de Cobrança";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Editar">

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoVeiculosId" asp-items="Model.GruposVeiculos"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoVeiculosId"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Diário</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoDiario" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoDiario"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroPlanoDiario" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroPlanoDiario"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Controlado</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Quilômetros Disponíveis (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="QuilometrosDisponiveisPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="QuilometrosDisponiveisPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km Extrapolado (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroExtrapoladoPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroExtrapoladoPlanoControlado"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Livre</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Livre)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoLivre" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoLivre"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/Excluir.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesPlanoCobrancaViewModel

@{
	ViewBag.Title = "Excluir Plano de Cobrança";
}

<div class="col">
	<partial name="_Informacoes" model="Model"></partial>

	<form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
		<button class="btn btn-danger px-5">
			<i class="bi bi-trash-fill me-1"></i>
			Confirmar
		</button>

		<a class="btn btn-outline-primary px-5" asp-action="Listar">
			<i class="bi bi-arrow-return-left me-1"></i>
			Voltar
		</a>
	</form>
</div>

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/Inserir.cshtml
@model LocadoraDeVeiculos.WebApp.Models.FormularioPlanoCobrancaViewModel

@{
    ViewBag.Title = "Inserir Plano de Cobrança";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoVeiculosId" asp-items="Model.GruposVeiculos"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoVeiculosId"></span>
            </div>

            <hr>
            
            <h2 class="text-primary fw-semibold mb-0">Plano Diário</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoDiario" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoDiario"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km (Plano Diário)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroPlanoDiario" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroPlanoDiario"></span>
            </div>

            <hr>
            
            <h2 class="text-primary fw-semibold mb-0">Plano Controlado</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Quilômetros Disponíveis (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="QuilometrosDisponiveisPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="QuilometrosDisponiveisPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoControlado"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Preço por Km Extrapolado (Plano Controlado)</label>
                <input class="form-control mb-1" asp-for="PrecoQuilometroExtrapoladoPlanoControlado" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoQuilometroExtrapoladoPlanoControlado"></span>
            </div>

            <hr>

            <h2 class="text-primary fw-semibold mb-0">Plano Livre</h2>

            <div>
                <label class="control-label fw-semibold mb-1">Preço Diário (Plano Livre)</label>
                <input class="form-control mb-1" asp-for="PrecoDiarioPlanoLivre" type="number" step="0.01"/>
                <span class="text-danger fs-6" asp-validation-for="PrecoDiarioPlanoLivre"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/Listar.cshtml
@model IEnumerable<LocadoraDeVeiculos.WebApp.Models.ListarPlanoCobrancaViewModel>

@{
    ViewBag.Title = "Listagem de Planos de Cobrança";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="PlanoCobranca" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Novo Plano de Cobrança
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var planoVm in Model)
        {
            <div class="card col-lg-5 col-xl-4 px-0">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                    <h5 class="p-0">@planoVm.Id</h5>

                    <div class="text-end d-flex align-items-center gap-3">
                        <a title="Detalhes"
                           class="text-info-emphasis fs-5"
                           href="/PlanoCobranca/Detalhes/@planoVm.Id">
                            <i class="bi bi-search"></i>
                        </a>
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/PlanoCobranca/Editar/@planoVm.Id">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/PlanoCobranca/Excluir/@planoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">Grupo de Veículos: @planoVm.GrupoVeiculos</h5>
                    <p class="card-text">
                        Preço Diário (Diário): @planoVm.PrecoDiarioPlanoDiario.ToString("C2") <br />
                        Preço por Km (Diário): @planoVm.PrecoQuilometroPlanoDiario.ToString("C2") <br />
                        Km Disponíveis (Controlado): @planoVm.QuilometrosDisponiveisPlanoControlado Km(s)<br />
                        Preço Diário (Controlado): @planoVm.PrecoDiarioPlanoControlado.ToString("C2") <br />
                        Preço por Km Extrapolado (Controlado): @planoVm.PrecoQuilometroExtrapoladoPlanoControlado.ToString("C2") <br />
                        Preço Diário (Livre): @planoVm.PrecoDiarioPlanoLivre.ToString("C2")
                    </p>
                </div>
            </div>
        }
    </div>
</div>

LocadoraDeVeiculos.WebApp/Views/PlanoCobranca/_Informacoes.cshtml
@model LocadoraDeVeiculos.WebApp.Models.DetalhesPlanoCobrancaViewModel

<div class="row gap-3 my-3 my-xl-5">
	<label class="fs-4"><strong>Grupo de Veículos:</strong> @Model.GrupoVeiculos</label>

	<label class="fs-4"><strong>Preço Diário (Plano Diário):</strong> @Model.PrecoDiarioPlanoDiario.ToString("C2")</label>

	<label class="fs-4"><strong>Preço por Km (Plano Diário):</strong> @Model.PrecoQuilometroPlanoDiario.ToString("C2")</label>

	<label class="fs-4"><strong>Quilômetros Disponíveis (Plano Controlado):</strong> @Model.QuilometrosDisponiveisPlanoControlado km(s)</label>

	<label class="fs-4"><strong>Preço Diário (Plano Controlado):</strong> @Model.PrecoDiarioPlanoControlado.ToString("C2")</label>

	<label class="fs-4"><strong>Preço por Km Extrapolado (Plano Controlado):</strong> @Model.PrecoQuilometroExtrapoladoPlanoControlado.ToString("C2")</label>

	<label class="fs-4"><strong>Preço Diário (Plano Livre):</strong> @Model.PrecoDiarioPlanoLivre.ToString("C2")</label>

	<label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>